services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./data:/usr/src/frontend/data
    environment:
      NODE_ENV: development
